version: "3.8"

services:
  app:
    # image: php:8.2-fpm
    image: webdevops/php-nginx:8.2
    command: >
      bash -c "
        composer install &&
        php artisan serve --host=0.0.0.0 --port=8000
      "
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/timeflow-test-app
    volumes:
      - .:/var/www
    networks:
      - laravel
    ports:
      - "8000:8000"

  frontend:
    image: node:18
    container_name: timeflow_frontend
    restart: unless-stopped
    working_dir: /var/www/timeflow-front
    volumes:
      - .:/var/www
    networks:
      - laravel
    ports:
      - "3000:3000"
    depends_on:
      - app
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    command: >
      bash -c "
        npm install &&
        npm run dev -- --host 0.0.0.0 --port 3000
      "

  db:
    image: mysql:8
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
